name = "Fabric Lite 1.19"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1acec5493087e2a273694ff3f32a030d4b589379a2ca1e11baecdbe9477d5d72"

[versions]
fabric = "0.14.6"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19", "1.19-pre1", "1.19-pre2", "1.19-pre3", "1.19-pre4", "1.19-pre5", "1.19-rc1", "1.19-rc2"]
