name = "Bigpack 1.19"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeea0a3a61a5b47668192c80bc5e4a4b07e11d8290d17810a66e2c4b69b77157"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
