name = "survival_vanilla_pack"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5e8f52ea4faf0fbba05cf26a5e355a361bf95d517126a9bee20d56cae2e3e97"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
