name = "survival_vanilla_pack"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9692540b66798395c52784c01121ffe238234b990ec65bf0b834252eb53e1dbf"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
