name = "survival_vanilla_pack"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d7e996dd3914e2c0f2914ac4dc8fcd2730d77074ab710c786981e73e18a4ec3"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
