name = "Survival Server 1.19"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fa1503ea41443f033687cab9349524a6676c9bd256843b97b56366f6b25c06a"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
