name = "Survival Server 1.19"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "154b06e81aa92d25f5378bd8ecbf6c8cc8dd40a962610cdcb8d8fde52199c3b5"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
