name = "survival_vanilla_pack"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a7f0443fa63f210cdcf285adc24107c5aba034ecdc2d50a26f63b8d350c740"

[versions]
fabric = "0.14.6"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19", "1.19-pre1", "1.19-pre2", "1.19-pre3", "1.19-pre4", "1.19-pre5", "1.19-rc1", "1.19-rc2"]
