name = "1.19 Performance"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a03b0153a4628d506adbe9c3ffd42318a12233328375ad1dba8fa0282b91424a"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
