name = "1.19 Performance"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e828a6e8384b10346c51d4e8d5b57aad3c9cbe7bf1ff21c4bcfc91285e69ded"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
