name = "1.18.2 Performance"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a7c5e2a9b56c37e8b8b102b1fb06c5c144e720450824b4a29365aceba4f3d9b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
