name = "1.18.2 Performance"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbbcbf946ac3bcf9a0647de156370420c3d98b11e60997a005d46e6676f9050f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
