name = "1.18.2 Performance"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d8af6ad6250c7b839ad755d0ed1e5e13367a32545435bc93e4a2076badb3006"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
