name = "Fabric Lite 1.18.2"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c1a3125687fc3f9f363bc8ccaa8d58c3014cdcb5b499e1e3ecdd394479624dd"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.17", "1.17.1", "1.18", "1.18.1", "1.18.2"]
