name = "Fabric Lite 1.18.2"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a9993ae950baba2e76b6db923bf542d32e50d86d947084cad8f41dd04dcd10"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
