name = "Fabric Lite 1.18.2"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4e4658dd5a7f67ffd3104eed5ca5dbdc3701b2378869570aed96484e26ad74f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.17", "1.17.1", "1.18", "1.18.1", "1.18.2"]
