name = "Fabric Lite 1.18.2"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7081c416be012c40dec429e80e54a17ea773d97feca1ed94cfc30304cb467f2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
