name = "Fabric Lite 1.18.2"
author = "Wine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b236c7f8b8539686e6e865086b2ffcc1c1a5adc201bce24fd492ad793743c47"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
